AllCops:
  NewCops: enable

Metrics/AbcSize:
  Max: 34

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/PerceivedComplexity:
  Max: 16

Metrics/MethodLength:
  Max: 60 # Default is 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Lint/NonAtomicFileOperation:
  Enabled: true

Lint/Debugger:
  Enabled: true